/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstore;

import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author 72dabriks
 */
public class Main extends javax.swing.JFrame {
    
    public static boolean signupup = false;
    public static User currentuser;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LogInButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        SignUpButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LoginText = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Store");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 70)); // NOI18N
        jLabel1.setText("Book Store");
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(80, 120, 325, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore/books (2).png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(465, 52, 209, 189);

        ExitButton.setBackground(new java.awt.Color(255, 255, 255));
        ExitButton.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 0, 0));
        ExitButton.setText("EXIT");
        ExitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ExitButton);
        ExitButton.setBounds(20, 10, 120, 60);

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 2, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("It's books... buy 'em");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(120, 200, 260, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 710, 270);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Login");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 330, 80, 40);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 380, 160, 40);

        LogInButton.setBackground(new java.awt.Color(0, 0, 0));
        LogInButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        LogInButton.setForeground(new java.awt.Color(255, 255, 255));
        LogInButton.setText("Log in");
        LogInButton.setBorder(null);
        LogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LogInButton);
        LogInButton.setBounds(450, 450, 130, 60);

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));

        SignUpButton.setBackground(new java.awt.Color(255, 204, 204));
        SignUpButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        SignUpButton.setText("Sign up Here!");
        SignUpButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SignUpButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel4.setText("an account?");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel6.setText("Don't have");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(64, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(66, 66, 66)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel6)
                    .addContainerGap(184, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 270, 300, 270);

        LoginText.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        LoginText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginTextKeyPressed(evt);
            }
        });
        jPanel1.add(LoginText);
        LoginText.setBounds(460, 320, 200, 40);

        PasswordField.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        PasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordFieldKeyPressed(evt);
            }
        });
        jPanel1.add(PasswordField);
        PasswordField.setBounds(460, 380, 200, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(719, 577));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    // Login method
    
    private void LogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInButtonActionPerformed
        // TODO add your handling code here:
        InitLogin();
                                   
    }//GEN-LAST:event_LogInButtonActionPerformed

    // Opening sign up window
    
    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        // TODO add your handling code here:
        if(!signupup){
            Signup signup = new Signup();
            signup.setVisible(true);
            signupup = true;
        }
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void PasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            InitLogin();
        }
    }//GEN-LAST:event_PasswordFieldKeyPressed

    private void LoginTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginTextKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            InitLogin();
        }
    }//GEN-LAST:event_LoginTextKeyPressed

    
    private void InitLogin(){
        
        if(!signupup){
            String login = LoginText.getText();
            char[] password = PasswordField.getPassword();        

            if(login.trim().isEmpty() || password.length == 0){

                DialogFrame okbutton = new DialogFrame();
                JOptionPane.showMessageDialog(
                        okbutton, "No input in login or password",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE);

            }
            else{
                boolean nouser = true;

                for (User user : Bookstore.users) {
                    if(login.toLowerCase().equals(user.login) && Arrays.equals(password, user.password)){
                        currentuser = user;
                        if(user.is_admin){
                            AdminW window = new AdminW();
                            window.setVisible(true);
                        }
                        else{
                            CustomerW window = new CustomerW();
                            window.setVisible(true);
                        }
                        nouser = false;
                        dispose();
                    }
                }

                if(nouser){
                    DialogFrame okbutton = new DialogFrame();
                    JOptionPane.showMessageDialog(
                            okbutton, "No users found with that login or password",
                            "ERROR",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else{
            DialogFrame okbutton = new DialogFrame();
                    JOptionPane.showMessageDialog(
                    okbutton, "Please close the signup window first!",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton LogInButton;
    private javax.swing.JTextField LoginText;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
